<?php
// -------------------------------------------------------
// billing.php
// Customer-facing payment page linked in billing emails.
//
//   billing.php?building=LyndhurstH&type=woolsy&token=XYZ
//   billing.php?building=LyndhurstH&type=storage&token=XYZ
//
// Auth: token validated against config/{building}.json
//       (generated by billing-helpers.php, expires in 7 days)
// No session required — the token IS the auth.
//
// Flow:
//   GET  → show payment options
//   POST → create Stripe Checkout session → redirect to Stripe
// -------------------------------------------------------

define('CONFIG_DIR',   __DIR__ . '/config/');
define('SCRIPTS_URL',  'https://sheepsite.com/Scripts/');

// -------------------------------------------------------
// Helpers
// -------------------------------------------------------
function loadConfig(string $building): array {
  $file = CONFIG_DIR . $building . '.json';
  return file_exists($file) ? json_decode(file_get_contents($file), true) ?? [] : [];
}

function saveConfig(string $building, array $cfg): void {
  if (!is_dir(CONFIG_DIR)) mkdir(CONFIG_DIR, 0755, true);
  file_put_contents(CONFIG_DIR . $building . '.json', json_encode($cfg, JSON_PRETTY_PRINT));
}

function loadPricing(): array {
  $file = CONFIG_DIR . 'pricing.json';
  return file_exists($file) ? json_decode(file_get_contents($file), true) ?? [] : [];
}

function loadStripe(): array {
  $file = CONFIG_DIR . 'stripe.json';
  return file_exists($file) ? json_decode(file_get_contents($file), true) ?? [] : [];
}

function fmtBytes(int $bytes): string {
  if ($bytes >= 1073741824) return round($bytes / 1073741824, 2) . ' GB';
  if ($bytes >= 1048576)    return round($bytes / 1048576, 1)    . ' MB';
  return round($bytes / 1024) . ' KB';
}

// Months remaining from now to $isoDate, rounded up (minimum 1).
function monthsUntil(string $isoDate): int {
  $secs = strtotime($isoDate) - time();
  if ($secs <= 0) return 1;
  return (int)max(1, ceil($secs / (30.44 * 86400)));
}

// Create a Stripe Checkout session via the REST API.
// Returns ['url' => 'https://checkout.stripe.com/...'] on success
// or      ['error' => '...'] on failure.
function createStripeSession(string $secretKey, array $params): array {
  $ch = curl_init('https://api.stripe.com/v1/checkout/sessions');
  curl_setopt_array($ch, [
    CURLOPT_POST           => true,
    CURLOPT_POSTFIELDS     => http_build_query($params),
    CURLOPT_USERPWD        => $secretKey . ':',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_TIMEOUT        => 30,
    CURLOPT_HTTPHEADER     => ['Content-Type: application/x-www-form-urlencoded'],
  ]);
  $resp = curl_exec($ch);
  $err  = curl_error($ch);
  curl_close($ch);

  if ($err) return ['error' => 'Connection error: ' . $err];

  $data = json_decode($resp ?: '', true);
  if (!$data) return ['error' => 'Invalid response from Stripe'];
  if (isset($data['error'])) return ['error' => $data['error']['message'] ?? 'Stripe error'];
  if (empty($data['url']))   return ['error' => 'No checkout URL returned'];

  return ['url' => $data['url']];
}

// -------------------------------------------------------
// Validate params
// -------------------------------------------------------
$building = trim($_GET['building'] ?? '');
$type     = trim($_GET['type']     ?? '');
$token    = trim($_GET['token']    ?? '');

if (!$building || !preg_match('/^[a-zA-Z0-9_-]+$/', $building)
  || !in_array($type, ['woolsy', 'storage'], true) || !$token) {
  http_response_code(400);
  die('<p style="color:red;font-family:sans-serif;">Invalid link. Please use the link from your billing email.</p>');
}

// -------------------------------------------------------
// Token validation
// -------------------------------------------------------
$cfg        = loadConfig($building);
$storedTok  = $cfg['billingToken'] ?? [];
$tokenValid = !empty($storedTok['token'])
           && hash_equals($storedTok['token'], $token)
           && ($storedTok['type'] ?? '') === $type
           && strtotime($storedTok['expires'] ?? '0') > time();

if (!$tokenValid) {
  http_response_code(403);
?><!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Link Expired</title>
<style>body{font-family:sans-serif;max-width:500px;margin:4rem auto;padding:0 1rem;text-align:center;}
h1{font-size:1.4rem;} p{color:#555;}</style></head>
<body>
<h1>Link Expired or Invalid</h1>
<p>This billing link has expired or has already been used.</p>
<p>If you still need to make a payment, please contact <a href="mailto:admin@sheepsite.com">admin@sheepsite.com</a>.</p>
</body></html>
<?php
  exit;
}

// -------------------------------------------------------
// Load data
// -------------------------------------------------------
$pricing      = loadPricing();
$stripe       = loadStripe();
$stripeKey    = $stripe['secretKey'] ?? '';
$stripeReady  = (bool)$stripeKey;

$label        = ucwords(str_replace(['_', '-'], ' ', $building));
$renewalDate  = $cfg['renewalDate'] ?? null;
$contactEmail = $cfg['contactEmail'] ?? '';

// -------------------------------------------------------
// POST — create Stripe Checkout session
// -------------------------------------------------------
$postError  = '';
$successUrl = SCRIPTS_URL . 'billing-success.php?' . http_build_query([
  'building' => $building,
  'type'     => $type,
]);
$cancelUrl  = SCRIPTS_URL . 'billing.php?' . http_build_query([
  'building' => $building,
  'type'     => $type,
  'token'    => $token,
]);

// -------------------------------------------------------
// POST — fake pay (test mode — Stripe not configured)
// -------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$stripeReady) {

  require_once __DIR__ . '/invoice-helpers.php';

  // Existing open invoice from billing token (created when threshold email was sent)
  $pendingInvoiceId = $cfg['billingToken']['invoiceId'] ?? null;

  if ($type === 'woolsy') {
    $qty        = max(1, (int)($_POST['qty'] ?? 1));
    $credFile   = __DIR__ . '/faqs/woolsy_credits.json';
    $allCredits = file_exists($credFile) ? json_decode(file_get_contents($credFile), true) ?? [] : [];
    if (!isset($allCredits[$building])) $allCredits[$building] = ['allocated' => 1.0, 'used' => 0.0];
    $allCredits[$building]['allocated'] = round($allCredits[$building]['allocated'] + $qty, 4);
    file_put_contents($credFile, json_encode($allCredits, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

    $bCfg = loadConfig($building);
    unset($bCfg['woolsyBillingEmailSent'], $bCfg['billingToken']);
    saveConfig($building, $bCfg);

    $creditPrice = (float)($pricing['creditPrice'] ?? 0);
    $total       = round($qty * $creditPrice, 2);
    $lineItems   = [['description' => 'Woolsy Credits (' . $qty . ' credit' . ($qty !== 1 ? 's' : '') . ')', 'amount' => $total]];
    if ($pendingInvoiceId) {
      updateOpenInvoice($building, $pendingInvoiceId, $lineItems, $total);
      markInvoicePaid($building, $pendingInvoiceId, false);
    } elseif ($total > 0) {
      recordPaidInvoice($building, $lineItems, $total, 'online');
    }

  } else { // storage
    $tierIdx = (int)($_POST['tier'] ?? 0);
    $tiers   = $pricing['storageOptions'] ?? [];
    if (isset($tiers[$tierIdx])) {
      $tier     = $tiers[$tierIdx];
      $newBytes = (int)($tier['bytes'] ?? 0);
      $monthly  = (float)($tier['pricePerMonth'] ?? 0);
      $months   = $renewalDate ? monthsUntil($renewalDate) : 12;
      $total    = round($monthly * $months, 2);
      if ($newBytes > 0) {
        $bCfg = loadConfig($building);
        $bCfg['storageLimit'] = $newBytes;
        unset($bCfg['storageLimitEmailSent'], $bCfg['billingToken']);
        saveConfig($building, $bCfg);

        $tierLabel = $tier['label'] ?? fmtBytes($newBytes);
        $lineItems = [['description' => 'Storage Upgrade — ' . $tierLabel, 'amount' => $total]];
        if ($pendingInvoiceId) {
          updateOpenInvoice($building, $pendingInvoiceId, $lineItems, $total);
          markInvoicePaid($building, $pendingInvoiceId, false);
        } elseif ($total > 0) {
          recordPaidInvoice($building, $lineItems, $total, 'online');
        }
      }
    }
  }

  header('Location: ' . $successUrl);
  exit;
}

// -------------------------------------------------------
// POST — create Stripe Checkout session
// -------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $stripeReady) {

  if ($type === 'woolsy') {
    $qty         = max(1, (int)($_POST['qty'] ?? 1));
    $creditPrice = (float)($pricing['creditPrice'] ?? 0);
    $unitCents   = (int)round($creditPrice * 100);
    if ($unitCents <= 0) {
      $postError = 'Credit price not configured. Please contact SheepSite.';
    } else {
      $params = [
        'mode'                             => 'payment',
        'success_url'                      => $successUrl . '&session_id={CHECKOUT_SESSION_ID}',
        'cancel_url'                       => $cancelUrl,
        'line_items[0][price_data][currency]'              => 'usd',
        'line_items[0][price_data][unit_amount]'           => $unitCents,
        'line_items[0][price_data][product_data][name]'    => 'Woolsy Credits — ' . $label,
        'line_items[0][price_data][product_data][description]'
                                           => $qty . ' credit' . ($qty !== 1 ? 's' : ''),
        'line_items[0][quantity]'          => $qty,
        'metadata[building]'               => $building,
        'metadata[type]'                   => 'woolsy',
        'metadata[credits_to_add]'         => $qty,
        'customer_email'                   => $contactEmail,
      ];
      $result = createStripeSession($stripeKey, $params);
      if (isset($result['url'])) {
        header('Location: ' . $result['url']);
        exit;
      }
      $postError = $result['error'] ?? 'Unknown error';
    }

  } else { // storage
    $tierIdx   = (int)($_POST['tier'] ?? 0);
    $tiers     = $pricing['storageOptions'] ?? [];
    if (!isset($tiers[$tierIdx])) {
      $postError = 'Invalid storage tier selected.';
    } else {
      $tier      = $tiers[$tierIdx];
      $monthly   = (float)($tier['pricePerMonth'] ?? 0);
      $newBytes  = (int)($tier['bytes'] ?? 0);

      // Pro-rate to renewal date if set; otherwise charge 1 year
      $months    = $renewalDate ? monthsUntil($renewalDate) : 12;
      $totalCents= (int)round($monthly * $months * 100);

      if ($totalCents <= 0) {
        $postError = 'Storage price not configured. Please contact SheepSite.';
      } else {
        $tierLabel = $tier['label'] ?? fmtBytes($newBytes);
        $desc      = $months . ' month' . ($months !== 1 ? 's' : '')
                   . ($renewalDate ? ' (pro-rated through ' . date('M j, Y', strtotime($renewalDate)) . ')' : '');
        $params = [
          'mode'                             => 'payment',
          'success_url'                      => $successUrl . '&session_id={CHECKOUT_SESSION_ID}',
          'cancel_url'                       => $cancelUrl,
          'line_items[0][price_data][currency]'              => 'usd',
          'line_items[0][price_data][unit_amount]'           => $totalCents,
          'line_items[0][price_data][product_data][name]'    => 'Storage Upgrade — ' . $label,
          'line_items[0][price_data][product_data][description]'
                                             => $tierLabel . ' — ' . $desc,
          'line_items[0][quantity]'          => 1,
          'metadata[building]'               => $building,
          'metadata[type]'                   => 'storage',
          'metadata[new_bytes]'              => $newBytes,
          'customer_email'                   => $contactEmail,
        ];
        $result = createStripeSession($stripeKey, $params);
        if (isset($result['url'])) {
          header('Location: ' . $result['url']);
          exit;
        }
        $postError = $result['error'] ?? 'Unknown error';
      }
    }
  }
}

// -------------------------------------------------------
// Prepare display data
// -------------------------------------------------------
$creditPrice  = (float)($pricing['creditPrice']       ?? 0);
$storageTiers = $pricing['storageOptions'] ?? [];
$defaultLimit = (int)($pricing['storageDefaultLimit'] ?? 524288000);
$currentLimit = (int)($cfg['storageLimit'] ?? $defaultLimit);
$storageUsed  = (int)($cfg['storageUsed']  ?? 0);

// Pre-select the first tier larger than current limit
$preSelected  = 0;
foreach ($storageTiers as $i => $t) {
  if ((int)($t['bytes'] ?? 0) > $currentLimit) { $preSelected = $i; break; }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SheepSite — Billing</title>
  <style>
    * { box-sizing: border-box; }
    body       { font-family: sans-serif; max-width: 560px; margin: 3rem auto; padding: 0 1.25rem; }
    h1         { font-size: 1.4rem; margin-bottom: 0.25rem; }
    .subtitle  { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }
    .card      { border: 1px solid #ddd; border-radius: 8px; padding: 1.25rem; margin-bottom: 1.5rem; }
    .card h2   { font-size: 1rem; margin: 0 0 0.5rem; }
    .hint      { font-size: 0.82rem; color: #888; margin: 0 0 1rem; }
    .stat-row  { display: flex; gap: 2rem; margin-bottom: 1rem; flex-wrap: wrap; }
    .stat      { font-size: 0.85rem; }
    .stat b    { display: block; font-size: 1rem; color: #111; }
    label      { font-size: 0.875rem; font-weight: bold; display: block; margin-bottom: 0.3rem; }
    input[type=number] {
      padding: 0.4rem 0.6rem; border: 1px solid #ccc; border-radius: 4px;
      font-size: 1rem; width: 100px; }
    .tier-list { list-style: none; padding: 0; margin: 0 0 1rem; }
    .tier-item { margin-bottom: 0.5rem; }
    .tier-item label {
      display: flex; align-items: center; gap: 0.75rem; padding: 0.65rem 0.85rem;
      border: 1px solid #ddd; border-radius: 6px; cursor: pointer;
      font-weight: normal; font-size: 0.9rem; }
    .tier-item input[type=radio]:checked + label,
    .tier-item label:has(input[type=radio]:checked) {
      border-color: #0070f3; background: #f0f7ff; }
    .tier-name { font-weight: bold; flex: 1; }
    .tier-price { color: #555; font-size: 0.85rem; white-space: nowrap; }
    .tier-note  { font-size: 0.78rem; color: #888; }
    .btn       { display: block; width: 100%; padding: 0.65rem; background: #0070f3; color: #fff;
                 border: none; border-radius: 4px; font-size: 1rem; cursor: pointer; margin-top: 0.5rem; }
    .btn:hover { background: #005bb5; }
    .btn:disabled { background: #aaa; cursor: not-allowed; }
    .error     { background: #ffeef0; color: #c00; padding: 0.65rem 0.85rem;
                 border-radius: 4px; font-size: 0.9rem; margin-bottom: 1rem; }
    .notice    { background: #fff3cd; color: #856404; padding: 0.65rem 0.85rem;
                 border-radius: 4px; font-size: 0.85rem; margin-bottom: 1rem; }
    .total-line { font-size: 0.85rem; color: #555; margin-bottom: 0.75rem; }
    .total-line strong { color: #111; }
    .stripe-note { font-size: 0.78rem; color: #888; text-align: center; margin-top: 0.75rem; }
  </style>
</head>
<body>

<h1>SheepSite — Billing</h1>
<div class="subtitle"><?= htmlspecialchars($label) ?></div>

<?php if ($postError): ?>
  <div class="error"><?= htmlspecialchars($postError) ?></div>
<?php endif; ?>

<?php if (!$stripeReady): ?>
  <div class="notice"><strong>Test mode</strong> — Stripe is not configured. Use "Fake Pay" to simulate a completed payment and test the full end-to-end flow.</div>
<?php endif; ?>

<?php if ($type === 'woolsy'): ?>

<!-- ====== WOOLSY ====== -->
<div class="card">
  <h2>Woolsy Credit Top-Up</h2>
  <p class="hint">Credits power Woolsy's AI answers. 1 credit = $<?= number_format($creditPrice, 2) ?>.</p>

  <?php
  $allCredits = [];
  $credFile   = __DIR__ . '/faqs/woolsy_credits.json';
  if (file_exists($credFile)) $allCredits = json_decode(file_get_contents($credFile), true) ?? [];
  $wc      = $allCredits[$building] ?? [];
  $wAlloc  = (float)($wc['allocated'] ?? 1.0);
  $wUsed   = (float)($wc['used']      ?? 0);
  $wRemain = max(0, $wAlloc - $wUsed);
  ?>
  <div class="stat-row">
    <div class="stat">Allocated<b><?= number_format($wAlloc, 2) ?></b></div>
    <div class="stat">Used<b><?= number_format($wUsed, 2) ?></b></div>
    <div class="stat">Remaining<b><?= number_format($wRemain, 4) ?></b></div>
  </div>

  <form method="post">
    <label for="qty">Credits to add</label>
    <input type="number" id="qty" name="qty" min="1" max="1000" value="10" required>
    <div class="total-line" id="woolsy-total">
      Total: <strong>$<?= number_format($creditPrice * 10, 2) ?></strong>
    </div>
    <button type="submit" class="btn">
      <?= $stripeReady ? 'Pay with Card →' : 'Fake Pay →' ?>
    </button>
  </form>
  <p class="stripe-note"><?= $stripeReady ? 'Powered by Stripe.' : 'Test mode — no real payment processed.' ?> Credits are applied automatically after payment.</p>
</div>

<script>
document.getElementById('qty').addEventListener('input', function() {
  var qty = Math.max(1, parseInt(this.value) || 1);
  var price = <?= json_encode(round($creditPrice, 2)) ?>;
  document.getElementById('woolsy-total').innerHTML =
    'Total: <strong>$' + (price * qty).toFixed(2) + '</strong>';
});
</script>

<?php else: // storage ?>

<!-- ====== STORAGE ====== -->
<div class="card">
  <h2>Storage Upgrade</h2>
  <?php if ($renewalDate): ?>
    <p class="hint">Choose a new storage tier. You will be charged the monthly fee for the
    remaining months of your current billing cycle only
    (<?= monthsUntil($renewalDate) ?> month<?= monthsUntil($renewalDate) !== 1 ? 's' : '' ?>,
    through <?= date('M j, Y', strtotime($renewalDate)) ?>).
    At renewal, storage is included in your annual invoice.</p>
  <?php else: ?>
    <p class="hint">Choose a new storage tier. You will be charged the monthly fee × 12 months.</p>
  <?php endif; ?>

  <div class="stat-row">
    <div class="stat">Current limit<b><?= fmtBytes($currentLimit) ?></b></div>
    <div class="stat">Used<b><?= $storageUsed > 0 ? fmtBytes($storageUsed) : '—' ?></b></div>
    <?php if ($renewalDate): ?>
      <div class="stat">Renewal<b><?= htmlspecialchars(date('M j, Y', strtotime($renewalDate))) ?></b></div>
    <?php endif; ?>
  </div>

  <form method="post" id="storage-form">
    <ul class="tier-list">
    <?php foreach ($storageTiers as $i => $tier):
      $bytes    = (int)($tier['bytes'] ?? 0);
      $monthly  = (float)($tier['pricePerMonth'] ?? 0);
      $months   = $renewalDate ? monthsUntil($renewalDate) : 12;
      $total    = $monthly * $months;
      $tLabel   = $tier['label'] ?? fmtBytes($bytes);
      $isCurrent= $bytes === $currentLimit;
      $isSmaller= $bytes < $currentLimit;
    ?>
    <li class="tier-item">
      <label>
        <input type="radio" name="tier" value="<?= $i ?>"
               <?= $i === $preSelected ? 'checked' : '' ?>
               <?= $isSmaller ? 'disabled' : '' ?>>
        <span class="tier-name"><?= htmlspecialchars($tLabel) ?><?= $isCurrent ? ' <span style="color:#888;font-weight:normal;">(current)</span>' : '' ?></span>
        <?php if ($isSmaller): ?>
          <span class="tier-note">below current limit</span>
        <?php elseif ($monthly > 0): ?>
          <span class="tier-price">
            $<?= number_format($total, 2) ?>
            <span class="tier-note">
              ($<?= number_format($monthly, 2) ?>/mo × <?= $months ?> mo<?= $renewalDate ? ' to renewal' : '' ?>)
            </span>
          </span>
        <?php else: ?>
          <span class="tier-note">Price not configured</span>
        <?php endif; ?>
      </label>
    </li>
    <?php endforeach; ?>
    </ul>

    <?php if (empty($storageTiers)): ?>
      <p style="color:#888;font-size:0.9rem;">No storage tiers configured. Contact SheepSite.</p>
    <?php else: ?>
      <button type="submit" class="btn">
        <?= $stripeReady ? 'Pay with Card →' : 'Fake Pay →' ?>
      </button>
    <?php endif; ?>
  </form>
  <p class="stripe-note"><?= $stripeReady ? 'Powered by Stripe.' : 'Test mode — no real payment processed.' ?> Storage is upgraded automatically after payment.</p>
</div>

<?php endif; ?>

</body>
</html>
